apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate  # Bind on PVC creation
# volumeBindingMode: WaitForFirstConsumer  # Bind on POD creation

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  local:
    path: /mnt/kubernetes/persistent_volumes/keycloak
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: keycloak-pvc
    namespace: develop
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: effiware.com/allow-creating-pv
          operator: In
          values:
          - "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: develop
spec:
  volumeName: keycloak-pv
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
